
server:
  port: 8088

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://pvinh.mysql.database.azure.com:3306/db_orchid?serverTimezone=UTC&allowPublicKeyRetrieval=True}
    username: ${SPRING_DATASOURCE_USERNAME:phuocvinh}
    password: ${SPRING_DATASOURCE_PASSWORD:root@1234}


#  datasource:
#    url: jdbc:mysql://localhost:3306/db_orchid
#    username: root
#    password: 12345

    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
    #properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
  mail:
    host: live.smtp.mailtrap.io
    username: api
    #spring.mail.password=your-email-password
    password: c10163364e93e30294bbb118d8a831aa
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
api:
  prefix: /api/v1

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true

data:
  format: "yyyy-MM-dd'T'HH:mm:ss.SSS"
jwt:
#  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
#  expiration: 10800 #30 min = 30 * 60
  expiration: 300 # 5p 5 * 30
  expiration-refresh-token: 5184000 #60 days = 60 * 24 * 60 * 60
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=
logging:
  level:
    org:
      springframework.security: DEBUG

#health check
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        #include: "health"
        include: "health, info"


#url return payment
HOST:
  URL: ${HOST_URL:https://orchid.fams.io.vn/api/v1}


